import type { Metadata } from "next";
import "./globals.css";
import { ReactQueryProvider } from "@/providers/react-query-provider";
import { HeaderComponent } from "@/components/header";
import { Press_Start_2P } from 'next/font/google'

export const metadata: Metadata = {
  title: "Pokedex",
  description: "Generated by create next app",
};

const pressStart2p = Press_Start_2P({
  weight: ["400"],
  subsets: ['latin'],
  display: 'swap'
})

export default function RootLayout({
  children,
  modal
}: Readonly<{
  modal: React.ReactNode;
  children: React.ReactNode;
}>) {


  return (
    <html lang="pt-br" className={pressStart2p.className}>
      <body>
        <ReactQueryProvider>
          <HeaderComponent />
          <div className="w-full flex justify-center items-center md:gap-9 h-full overflow-hidden py-9 px-7 relative bg-gradient-to-r from-red-500 via-red-600 to-red-700">
            {children}
            {modal}
          </div>
        </ReactQueryProvider>
      </body>
    </html >
  );
}
