import type { Metadata } from "next";
import "./globals.css";
import { ReactQueryProvider } from "@/providers/react-query-provider";
import { HeaderComponent } from "@/components/header";
import { isValidElement } from "react";


export const metadata: Metadata = {
  title: "Pokedex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal
}: Readonly<{
  modal: React.ReactNode;
  children: React.ReactNode;
}>) {


  return (
    <html lang="pt-br">
      <body>
        <ReactQueryProvider>
          <HeaderComponent />
          <div className="w-full flex justify-center items-center md:gap-9 h-full overflow-hidden py-9 px-7 relative bg-orange-peel-100">
            {children}
            {modal}
          </div>
        </ReactQueryProvider>
      </body>
    </html >
  );
}
